#include<iostream.h>
#include<conio.h>

void main()
{
 char 'c';
 float amnt,nrte,opt;
 float sil=5,gold=10,pla=25;
 cout<<"\nIf the payment is done from silver(5% disc.) card press.....S"
       "\nIf the payment is done from gold(10% disc.)  card press.....G"
       "\nIf the payment is done from platinum(25% disc.) card press..P";
 cin>>c;
 cout<<"\nEnter the amount of the that thing "
       "\nMinimum amount for card purchase is Rs.5000";
 cin>>amnt;
 switch(

